language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - node_modules
jobs:
  stages:
    - name: deploy
      deploy:
        provider: heroku
        api_key:
          secure: ${heroku_key}