language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - node_modules
stages:
  - name: deploy
    if: branch = master
    deploy:
      provider: heroku
      api_key:
        secure: ${heroku_key}